services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_REPO_URL: ${APP_REPO_URL:-https://github.com/contentauth/c2pasign.git}
    command: bash -lc "./run.sh"
    working_dir: /app
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - SKIP_DOCKER=1
