version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -lc "cd /app && bash run.sh 80"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - SKIP_DOCKER=1
